- name: Update Distro
  apt: 
    upgrade: yes
    update_cache: yes
  register: distro_update 
  when: update_distro == true

- name: Enable cgroups
  replace:
    path: /boot/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
    - "cgroup_memory=1"
    - "cgroup_enable=memory"
  register: enable_cgroup

- name: Reboot if upgraded or cgroup enabled
  reboot:
  when: distro_update.changed or enable_cgroup.changed 

- name: Flush iptables before switching to iptables-legacy from nftables
  iptables:
    flush: true
  changed_when: false   # iptables flush always returns changed

- name: Changing to iptables-legacy
  alternatives:
    path: /usr/sbin/iptables-legacy
    name: iptables

- name: Changing to ip6tables-legacy
  alternatives:
    path: /usr/sbin/ip6tables-legacy
    name: ip6tables

    # may not be necessary, revisit
    # requires gather_facts: true
    #    - name: Update the /etc/hosts file with node name
    #      lineinfile:
    #        path: "/etc/hosts"
    #        regexp: "127.0.0.1\t{{ hostvars[item]['ansible_hostname']}}"
    #        line: "{{ hostvars[item].ansible_default_ipv4.address }}\t{{ hostvars[item]['ansible_hostname']}}"
    #        state: present
    #        backup: yes
    #      with_items: "{{groups['cluster']}}"
