---
- hosts: cluster
  gather_facts: false
  become: yes

  vars:
    fetch_image_locally: false

  tasks:
    - name: Change boot order to SD card first
      include_role:
        name: change_boot_order
      vars:
        boot_order: "0xf25641"

    - name: Fetch RPi OS image
      include_role:
        name: fetch_rpi_image  # returns downloaded_image_path
        apply:
          delegate_to:  "{{ fetch_image_locally | ternary('localhost', inventory_hostname) }}"
          become: false
      vars:
        image_download_dir: /tmp

    - name: Copy image file to node
      copy:
        src: "{{ downloaded_image_path }}"
        dest: /tmp
      when: fetch_image_locally == true

    - name: Uncompress image file
      command:
        unxz -k -f "/tmp/{{ downloaded_image_path | basename }}"

    - name: Flash RPi OS image to NVME
      include_role:
        name: flash_rpi_image
      vars:
        image_path: "/tmp/{{ downloaded_image_path | basename | splitext | first }}"
        target_disk: /dev/nvme0n1
        hostname: "{{ inventory_hostname }}" 

    - name: Change boot order to NVME card first
      include_role:
        name: change_boot_order
      vars:
        boot_order: "0xf25146"
