---
- hosts: cluster
  gather_facts: false
  become: true
  tasks:
    - name: Preinstall cluster nodes setup
      include_role:
        name: rpi/k3s_preinstall

- hosts: k3s_server
  gather_facts: false
  become: true
  tasks:
    - name: Configure the control plane node
      include_role:
        name: k3s/server

- hosts: k3s_agent
  gather_facts: false
  become: true
  tasks:
    - name: Configure the worker nodes
      include_role:
        name: k3s/agent
