- name: Resolve boot order string
  script: ./get_boot_order_string.sh "{{ boot_order | default('') }}" "{{ boot_from | default('') }}"
  register: boot_order_string 

- name: Cleanup script output
  set_fact:
    boot_string: "{{ boot_order_string.stdout | trim }}"

- name: Change boot order
  include_tasks: 
    file: change_boot_order.yml
  when: boot_string != "skip"
