---
- hosts: all
  gather_facts: false
  become: yes

  vars:
    ansible_user: pi

  tasks:
    - name: Change boot order to nvme first
      include_role:
        name: rpi/change_boot_order
      vars:
        boot_order: "0xf25146"
        reboot: true
#ansible-playbook reboot_to_nvme.yml -i node4,
