- name: Set Longhorn delete confirmation flag to "true"
  kubernetes.core.helm:
    name: "{{ longhorn_release_name }}"
    chart_ref: "{{ longhorn_chart_ref }}"
    chart_version: "{{ longhorn_version| default(omit) }}"
    release_namespace: "{{ longhorn_namespace }}"
    create_namespace: true
    values:
      defaultSettings:
        defaultDataPath: "{{ longhorn_data_path }}"
        deletingConfirmationFlag: true

- name: Uninstall Longhorn
  kubernetes.core.helm:
    name: "{{ longhorn_release_name }}"
    chart_ref: "{{ longhorn_chart_ref }}"
    chart_version: "{{ longhorn_version| default(omit) }}"
    release_namespace: "{{ longhorn_namespace }}"
    state: absent

