- name: Add Longhorn Helm Repo
  kubernetes.core.helm_repository:
    repo_name: "{{ longhorn_helm_repo_name }}"
    repo_url: "{{ longhorn_helm_repo_url }}"

- name: Install Longhorn
  kubernetes.core.helm:
    name: "{{ longhorn_release_name }}"
    chart_ref: "{{ longhorn_chart_ref }}"
    chart_version: "{{ longhorn_version| default(omit) }}"
    release_namespace: "{{ longhorn_namespace }}"
    create_namespace: true
    values:
      defaultSettings:
        defaultDataPath: "{{ longhorn_data_path }}"
